const ROUTES = {
  // stack

  // HOME
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',

  // NEWS SCREEN
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
};

export default ROUTES;
