const ROUTES = {
  // stack
  MAIN_STACK: 'MAIN_STACK',
  AUTHORIZED_STACK: 'AUTHORIZED_STACK',
  UNAUTHORIZED_STACK: 'UNAUTHORIZED_STACK',
  HOME_STACK: 'HOME_STACK',
  PROFILE_STACK: 'PROFILE_STACK',
  // HOME
  HOME_SCREEN: 'HOME_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  PERSONAL_INFO_SCREEN: 'PERSONAL_INFO_SCREEN',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',

  // NEWS SCREEN
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  USER_PROFILE: 'USER_PROFILE',
};

export default ROUTES;
