export interface ROUTES_TYPE {
  // stack
  MAIN_STACK: 'MAIN_STACK';
  AUTHORIZED_STACK: 'AUTHORIZED_STACK';
  UNAUTHORIZED_STACK: 'UNAUTHORIZED_STACK';
  HOME_STACK: 'HOME_STACK';
  PROFILE_STACK: 'PROFILE_STACK';

  //home
  HOME_SCREEN: 'HOME_SCREEN';
  PROFILE_SCREEN: 'PROFILE_SCREEN';
  PERSONAL_INFO_SCREEN: 'PERSONAL_INFO_SCREEN';
  LOGIN_SCREEN: 'LOGIN_SCREEN';
  REGISTER: 'REGISTER';
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN';
  // AUTHENTICATION SCREENS

  FORGOT_PASSWORD: 'FORGOT_PASSWORD';
  USER_PROFILE: 'USER_PROFILE';
}

const ROUTES: ROUTES_TYPE = {
  // stack
  MAIN_STACK: 'MAIN_STACK',
  AUTHORIZED_STACK: 'AUTHORIZED_STACK',
  UNAUTHORIZED_STACK: 'UNAUTHORIZED_STACK',
  HOME_STACK: 'HOME_STACK',
  PROFILE_STACK: 'PROFILE_STACK',
  // HOME
  HOME_SCREEN: 'HOME_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  PERSONAL_INFO_SCREEN: 'PERSONAL_INFO_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER: 'REGISTER',
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',

  // NEWS SCREEN
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  USER_PROFILE: 'USER_PROFILE',
};

export const ROUTE_TABS = {
  MAIN_TAB: 'MAIN_TAB',
  PAYMENT_RESPONSE: 'PAYMENT_RESPONSE',
};
export default ROUTES;
